### ISSUE TITLE
How to import build files from lib to another React App

### ISSUE THREAD

**Issue by dennyjohnk** [Wolox/react-chat-widget#109]
Hi,
Am trying to import the chat widget to [.](https://github.com/facebook/create-react-app#creating-an-app)

Instead of importing it through npm package like
` import { Widget } from 'react-chat-widget';`

Am trying to import it from the build folder 
`import { Widget } from './lib';`

Which has the build files ( index.js , styles.css)

Currently am getting multiple errors like 
` 'define' is not defined    `

What is the mistake am doing ?

**Comment by moelahmady** [comment]
Did you figured out how ??

**Comment by dennyjohnk** [comment]
Nope :( U can only import this as npm package
