### ISSUE TITLE
how to delete all loaded messages

### ISSUE THREAD

**Issue by saikatharryc** [Wolox/react-chat-widget#113]
is there any way to delete the messages ?
in my use case, there can be multiple session, and now, when i'm lunching the app and starting conversation. then after ending this , i'm taking data from another data source. and i want to load all thoda, and unload previous messages.

**Comment by trangelier** [comment]
Hey I ran into this yesterday!! 

You can pull in a method `dropMessages` from `react-chat-widget` and call it which will clear the messages! I do this in my `componentDidMount` in my wrapper component which is my widget.

```js
import {
	Widget,
	addResponseMessage,
	dropMessages,
	renderCustomComponent,
	toggleWidget
} from 'react-chat-widget';

.........

	componentDidMount() {
		dropMessages(); // clears any messages left in state
		toggleWidget(); // toggles the widget open on load
                .........
```

No clue why this isn't in the Readme, I thought about doing a PR for it but 😅
