### ISSUE TITLE
Widget Open Event

### ISSUE THREAD

**Issue by dennyjohnk** [Wolox/react-chat-widget#114]
Is there any way to know whether the widget is Open or Closed ?

**Comment by gl36** [comment]
// 组件加载完成
  componentDidMount() {
    //调用组件内部方法打开窗口，再次调用是关闭；在组件销毁时调用一次，可以保证每次打开都是开启状态
    toggleWidget();
}

 //组件即将销毁
  componentWillUnmount() {
    //调用组件内部方法打开窗口，再次调用是关闭；在组件销毁时调用一次，可以保证每次打开都是开启状态
    toggleWidget();
  }

**Comment by petarzoric** [comment]
Have the same issue.

**Comment by cosmeoes** [comment]
I found a work around for this. First I created and empty component, with two callback, one will be called when the component mounts and the other when it unmounts.
```javascript
class ReadListener extends Component {
  componentDidMount() {
    this.props.onOpen()
  }
  componentWillUnmount() {
    this.props.onClose()
  }
  render() {
    return (null)
  }
}
```

Next I just added to the chat with `renderCustomComponent`
```javascript
renderCustomComponent(ReadListener, {onOpen: this.chatOpenedHandler, onClose: this.chatClosedHandler })
```
Here's a basic example that prints to the console "opened" when it opens and "closed" when it closes.
```javascript
import React, { Component } from 'react';
import './App.css';
import { Widget, renderCustomComponent } from 'react-chat-widget';

import 'react-chat-widget/lib/styles.css';

class ReadListener extends Component {
  componentDidMount() {
    this.props.onOpen()
  }
  componentWillUnmount() {
    this.props.onClose()
  }
  render() {
    return (null)
  }
}

class App extends Component {
  componentDidMount() {
    renderCustomComponent(ReadListener, {onOpen: this.chatOpenedHandler, onClose: this.chatClosedHandler })
  }
  
  chatOpenedHandler() {
    console.log("opened")
  }
  chatClosedHandler() {
    console.log("closed")
  }
   
  render() {
    return (
      <div className="App">
        <Widget/>
      </div>
    );
  }
}

export default App;
```

**Comment by jonangelocomia** [comment]
this works for me

`  useEffect(() => { 
    toggleWidget();
    return () => {
      toggleWidget();
    };
  },[]);`

**Comment by luddilo** [comment]
I can't get the solution @cosmeoes proposed to work, the only difference I can think of is that my parent component is functional. The widget starts hidden so renderCustomComponent never does anything. Ideas of how to get around this? 

@mcallegari10 do you have ideas of a more elegant solution to this perhaps?

**Comment by Valkyrihane** [comment]
@luddilo

Import `isWidgetOpened` from **'react-chat-widget'** and use it as a function
```JS
import { isWidgetOpened } from 'react-chat-widget';

if (isWidgetOpened()) return 'foo';
```

I have no idea why this function is not documented however.

**Comment by luddilo** [comment]
Thanks @Valkyrihane, I found this method but would need a listener since I don't want to poll this method over and over.

**Comment by HumayounBaig** [comment]
hey there do we have any update on this i really need an onClose listener right now

**Comment by Lipseys** [comment]
We found a more elegant solution to creating a listener. 

![image](https://user-images.githubusercontent.com/57908806/98950668-e6d46f00-24be-11eb-9e8a-c5219638dc3b.png)
