### ISSUE TITLE
Each child in a list should have a unique "key" prop issue for Custom Launcher

### ISSUE THREAD

**Issue by dennyjohnk** [Wolox/react-chat-widget#116]
Hi,
Am trying to build a custom laumcher like below :

**getCustomLauncher = handleToggle => (
    <Launcher
      toggle={handleToggle}
      onClick={function(e) {
        this.handleBotToggle.bind();
      }}
    />
  );**

  **render() {
    return (
      <div className="App">
        <Widget
          handleNewUserMessage={this.handleNewUserMessage}
          profileAvatar={this.state.profileAvatar}
          title={this.state.title}
          subtitle={this.state.subtitle}
          senderPlaceHolder={this.state.senderPlaceHolder}
          autofocus={this.state.autofocus}
          launcher={handleToggle => this.getCustomLauncher(handleToggle)}
        />
      </div>
    );
  }**

Below is my launcher code :

import React from "react";
import PropTypes from "prop-types";
import { connect } from "react-redux";

import openLauncher from "./assets/launcher_button.svg";
import close from "./assets/clear_button.svg";

const Launcher = ({ toggle, chatOpened }) => (
  <button
    type="button"
    className={chatOpened ? "rcw-launcher rcw-hide-sm" : "rcw-launcher"}
    onClick={toggle}
  >
    {chatOpened ? (
      <img src={close} className="rcw-close-launcher" alt="" />
    ) : (
      <img src={openLauncher} className="rcw-open-launcher" alt="" />
    )}
  </button>
);

Launcher.propTypes = {
  toggle: PropTypes.func,
  chatOpened: PropTypes.bool
};

export default connect(store => ({
  chatOpened: store.behavior.get("showChat")
}))(Launcher);

But am getting the error `Each child in a list should have a unique "key" prop`
Am not using any array anyway. What is the mistake here ?

**Comment by allaaaaan** [comment]
Hi @dennyjohnk , getting the same issue here and saw you marked this as completed. Any update or solution for this issue? Thanks in adcance
