### ISSUE TITLE
Clear text input

### ISSUE THREAD

**Issue by adantoscano** [Wolox/react-chat-widget#12]
I'm trying your awesome widget but when I submit any text, it keeps in the input. How can I solve it?

**Comment by mcallegari10** [comment]
Thanks for the heads up! You can access and clear the value in the input like this:

```js
document.getElementsByClassName('sender')[0].message.value = ''
```

You should do it when the `handleNewUserMessage` prop is called. Sorry for the inconvenience, this will be fixed in the next version :smile:

**Comment by adantoscano** [comment]
Nothing to apologise, thanks for the answer!
