### ISSUE TITLE
Declaration file for use in TypeScript project

### ISSUE THREAD

**Issue by mike-barnett** [Wolox/react-chat-widget#122]
I am trying to use react-chat-widget from within a TypeScript project, but am getting complaints that there is no declaration file. When I try the suggested command to install the types, I get a response from npm that the repository does not contain anything for it. Would it be possible to add a declaration file?

`TypeScript error in C:/dev/Bugs/React/chat2/src/App.tsx(4,24):
Could not find a declaration file for module 'react-chat-widget'. 'C:/dev/Bugs/React/chat2/node_modules/react-chat-widget/lib/index.js' implicitly has an 'any' type.
  Try 'npm install @types/react-chat-widget' if it exists or add a new declaration (.d.ts) file containing 'declare module 'react-chat-widget';'  TS7016`

**Comment by stevemao** [comment]
I have added types to DefinitelyTyped. You can now `npm install @types/react-chat-widget`. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42344 😄

**Comment by mike-barnett** [comment]
Thanks so much! Very nice!
