### ISSUE TITLE
Change icon of launcher button

### ISSUE THREAD

**Issue by CKanishka** [Wolox/react-chat-widget#123]
How can I change the launcher button's icon?

**Comment by pranavmodx** [comment]
@CKanishka Hi, did you solve it? I'm having the same issue.

**Comment by pranavmodx** [comment]
Ohk, nevermind. Got it. You just need to create a custom launcher like so :

function MyApp() {
  const getCustomLauncher = (handleToggle) =>
    <button onClick={handleToggle}>This is my launcher component!</button>

  return (
    <Widget
      ...
      launcher={handleToggle => getCustomLauncher(handleToggle)}
    />
  )
}

**Comment by pranavmodx** [comment]
Wrap return value of 'getCustomerLauncher' inside a 'button' field. Donno why Github is taking it off.
