### ISSUE TITLE
Time / date stamp

### ISSUE THREAD

**Issue by Dobby89** [Wolox/react-chat-widget#133]
## Feature request
Add timestamps to each post. Additionally have the ability to get/set the timestamp of each post.

For example I want to populate the chat from a database of the user's chat history and I need to add the date and time of each message.

**Comment by fortesl** [comment]
That has been done long time ago. Just create a custom date component - example:
```
const CurrentDate = ({date}) => {
    return new Date().getDate() !== new Date(date).getDate()
        ? new moment(date).format('LT')
        : new moment(date).format('ddd LT');
};
```
Then use the renderCustomComponent message to display the date after you send a message -example:

`            addResponseMessage(message.content);
            renderCustomComponent(CurrentDate, {date: message.date});`

**Comment by mcallegari10** [comment]
We are adding timestamp on the next version but that's a cool way to add a custom timestamp 😄

**Comment by Bonfims** [comment]
the added feature ir not completely like @Dobby89 suggest, can some of you tell me how we can do like below:

"For example I want to populate the chat from a database of the user's chat history and I need to add the date and time of each message."

**Comment by bhavinkatira123** [comment]
What if i want to add custom timestamp into addUserMessage() function ?

**Comment by lfp97** [comment]
> 
> 
> What if i want to add custom timestamp into addUserMessage() function ?

`addUserMessage()` only accepts strings, but you can do as @fortesl suggested and render your own timestamp:

```javascript
import { Widget, addUserMessage, renderCustomComponent} from 'react-chat-widget'

...

const CustomTimeStampFragment = ({date}) => {
	return (
		<div style={{fontSize: 12}}>
			{new moment(date).format('DD/MM/yyyy')}
		</div>
	)
}
addUserMessage(yourString)
renderCustomComponent(CurrentDate, {date: message.date})

...
```

**Comment by Krisslk** [comment]
> We are adding timestamp on the next version but that's a cool way to add a custom timestamp 😄

hey I just want to know, let say there are already send messages from our side, I need to show then in the right hand side, can you provide a guide or reference doc to achieve my goal
