### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by Dobby89** [Wolox/react-chat-widget#134]
## Feature request
A method to add a temporary typing indicator to the bottom of the message list so the user knows a response is being created.

For example, an asynchronous request is made before a reply can be posted, but it would be good for the user to know that their message is being dealt with.

**Comment by fortesl** [comment]
use the renderCustomComponent method to display whatever you want!

**Comment by rabidgremlin** [comment]
There is the _toggleMsgLoader()_ method. Doesn't seem to be documented but it does what you want @Dobby89 

See https://github.com/Wolox/react-chat-widget/blob/f0715ad7ad4fcdacc67e5d1e3ced9624a8f19454/dev/App.js#L10 for example usage
