### ISSUE TITLE
have chatbox open without clicking the launcher button

### ISSUE THREAD

**Issue by bradleyy1012** [Wolox/react-chat-widget#15]
Hello, 
I'm not sure if this is the place to post this since it's not an "issue", but is there a way that I can have the chat window open when the page loads, rather than having to click the launcher button for it to open?

**Comment by mcallegari10** [comment]
Greetings! That's actually a "feature" I've been thinking about, so surely it will be added in the next version. For now, I can offer you a more jQuery-ish solution:

```js
document.getElementsByClassName('launcher')[0].click()
```

Thanks for the heads up! :smile:

**Comment by mcallegari10** [comment]
This feature request has been addressed in v2.1.0
