### ISSUE TITLE
Typescript no type definition

### ISSUE THREAD

**Issue by inventivejon** [Wolox/react-chat-widget#152]
Workaround.
1. Add 
"paths": {
        "*" : ["src/@custom_types/*"]
    },
to your tsconfig.json

2. Add a folder named @custom_types to your src folder.
3. Add a file named react-chat-widget.d.ts and insert the following content:
import { Widget } from 'react-chat-widget';

declare module 'react-chat-widget'{
    class Widget extends React.Component<SimpleSelectProps, any> {}
    function addResponseMessage(input: String): any;
    function toggleMsgLoader();
    function setQuickButtons(input: Array<any>): any;
    function addUserMessage(input: String): any;
    function toggleWidget(): any;
}
4. Hit save and now all should work.

**Comment by pingai-github** [comment]
It does not work for me using create-react-app

**Comment by stevemao** [comment]
It does not work for me using create-react-app

**Comment by inventivejon** [comment]
Check here: https://github.com/inventivejon/ExSyNL/tree/master/Frontend

**Comment by stevemao** [comment]
I'll have a look. Thanks!

**Comment by stevemao** [comment]
I have added types to DefinitelyTyped. You can now `npm install @types/react-chat-widget`. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42344 😄

**Comment by inventivejon** [comment]
Cool thx :)

**Comment by inventivejon** [comment]
Works fine. Good job!
