### ISSUE TITLE
Doesn't work on mobile devices properly unless scaled

### ISSUE THREAD

**Issue by naser-baig-au4** [Wolox/react-chat-widget#164]
Hi,

It doesn't seem to scale properly on mobile. I tested it on my mobile (Galaxy S8) as well as the responsive dev tools in firefox but to no avail.

The layout scales down a lot. It's not adjusting to it's specified width as per the viewport. I see multiple media queries for widths less than 800px (tried removing them all but that doesn't fix the issue).

What's weird is, it scales properly and works great the moment I make minor scaling adjustments. I'd really appreciate any help in this regard.

Here's a video explaining the issue: https://www.dropbox.com/s/x49syd8ihwtzzd0/Chatbot%20mobile%20issue.mp4?dl=0

**Comment by Mzaien** [comment]
what was the solution i had the same problem and detach it @naser-baig-au4

**Comment by naser-baig-au4** [comment]
I forgot to include the meta viewport tag @Mzaien 

<meta name="viewport" content="width=device-width, initial-scale=1.0">

Doing this fixed it for me.
