### ISSUE TITLE
I am getting an error "Invalid hook call" when I am trying to render widget.

### ISSUE THREAD

**Issue by kashish-jain** [Wolox/react-chat-widget#178]
I am not sure why this is happening. I am not using any hooks in my components. 
This is how my App component's render's return look like.

    return (
      <>
        <div className="App">
          {component}
           <Widget handleNewUserMessage={this.handleNewUserMessage} /> 
        </div>
      </>

I do not get any error if I do not render Widget component. I am working on some project and I upon reading the documentation, I think this is exactly what I am looking for. Could you please help me asap in fixing this?

**Comment by mcallegari10** [comment]
Hi! Let me see if I can replicate it. Are you using the version 3.0?

**Comment by kashish-jain** [comment]
Hi thanks for the reply. I am not sure what the issue was, but it got resolved by itself. May be I was not updating my node_modules or something, but appreciate the quick reply. You can close this issue.
Keep up the good work, I was looking exactly for some chat component like this.

**Comment by masterbater** [comment]
Reopening, I also encountered this issue.

**Comment by amitsingh0542** [comment]
@kashish-jain i was having same issue and understood the problem. It's causing the issue because of 2 different version of react. your project might be having x version of react and chat widget have y version of react. 
cc: @mcallegari10 If we can add the alias for react so it might solve the problem.
