### ISSUE TITLE
react and react-dom error

### ISSUE THREAD

**Issue by ArthurVerstraete** [Wolox/react-chat-widget#183]
Adding the react and react-dom package to your package is giving errors in our site, how can we fix this please?

![image](https://user-images.githubusercontent.com/36663371/80943394-633b1680-8de7-11ea-828b-2b7dbe087873.png)

**Comment by ArthurVerstraete** [comment]
Fixed with v3.0.1, thank you for that! But now I'm having other problems, see #182

**Comment by mcallegari10** [comment]
Awesome! I'll check that other issue 😄
