### ISSUE TITLE
Resetting the QuickButtons

### ISSUE THREAD

**Issue by SirBenedick** [Wolox/react-chat-widget#188]
Hey thanks for maintaining this repo, it works like a charm.
There is one thing I am currently struggling with.

It is possible to set quick reply buttons with the setQuickButtons().
But it seems to be impossible to remove the existing QuickButtons. 
setQuickButtons() seems to append the existing array and not replace it. Therefore the user is always displayed all the previous QuickButtons.

Is there a way to reset the QuickButtons? And if not could this be added?

I think it is quite useful to have QuickButtons assist depending on a certain message.
If this is not possible or it shouldn't be implement I will switch to renderCustomComponent() and "rebuild" this feature.

Ben

**Comment by mcallegari10** [comment]
Hi! Thank you for your kind words. Regarding the issue with the quick buttons, I've created #189 that should fix the lacking of the reset functionality. Should be published in the next version 😄. Sorry for the inconvenience!

**Comment by SirBenedick** [comment]
Thanks Martin 🙏 
Any ETA on the next version?

**Comment by mcallegari10** [comment]
I'll publish it tomorrow 😄
