### ISSUE TITLE
renderCustomComponent props formating

### ISSUE THREAD

**Issue by adantoscano** [Wolox/react-chat-widget#19]
Hi again,

I'm trying renderCustomComponent feature but idk how to send props.
I tried ``` renderCustomComponent(Button,{color:"primary"}); ``` but didn't work

**Comment by mcallegari10** [comment]
Hello! I tested it and it's supposed to be working. You should be doing something like:

```js
// Your Button component
const Button = ({ color, handleClick }) =>
  <button type="button" className={`${color}`} onClick={handleClick}>
    This is a button!
  </button>;

// The component that controls what's going to be rendered
class App extends React.Component {
  ...
  someMethod() {
    renderCustomComponent(Button, { color: "primary", handleClick: this.handleClick});
  }
  ...
```

The Button component should be rendered :smile:

**Comment by adantoscano** [comment]
that works!!!

Thanks again :)

**Comment by dennyjohnk** [comment]
How to remove a custom component ?

**Comment by EdmarPereira** [comment]
> ```js
> renderCustomComponent(Button, { color: "primary", handleClick: this.handleClick});
> ```

Thanks a lot this helps me a lot to solve my problem
