### ISSUE TITLE
Possibility of integration with theme-ui

### ISSUE THREAD

**Issue by danhab99** [Wolox/react-chat-widget#190]
I'd love to be able to restyle this widget with my already existing [`theme-ui`](https://theme-ui.com/) setup. Any possibility of doing so?

**Comment by mcallegari10** [comment]
Hi! We can add a themes feature but it will take some time. You can submit a PR if you want to, I'll gladly check it out. In the meantime, I suggest applying your styles via CSS. It's not really the same, but it'll do the trick.
