### ISSUE TITLE
Clear Chat or Exit 

### ISSUE THREAD

**Issue by amitsingh0542** [Wolox/react-chat-widget#191]
DeleteMessage delete message only based on Id. There should be option to clear complete chat or exit to clear complete message.

**Comment by zarandonlautaro** [comment]
You can use

`import { dropMessages } from 'react-chat-widget';
class MyWidget extends Component {
      state={}
     componentDidMount(){}
     render(){
     dropMessages();
            return (<Widget/>)
     }
}`

**Comment by amitsingh0542** [comment]
@zarandonlautaro wow super cool!! i really missed this one. Thank a ton 💯

**Comment by zarandonlautaro** [comment]
No problem! Close the Issue
