### ISSUE TITLE
handleTextInputChange doesn't seem to work

### ISSUE THREAD

**Issue by naser-baig-au4** [Wolox/react-chat-widget#199]
Hi,

I need to apply a validation for all the user inputs and I tried using the supplied prop handleTextInputChange to trigger a function. However, it doesn't seem to work. Could you please let me know if there's a mistake in the way I am using that prop or triggering the function?

Here's the corresponding piece from my code base:

```
handleTextInputChange = (e) => {
    console.log("I am called", e);
  };

render() {
    return (
      <div id="my-chat-widget">
        <Widget
          handleNewUserMessage={this.handleNewUserMessage}
          handleTextInputChange={this.handleTextInputChange}
        />
      </div>
    );
  }
```

I'd really appreciate any help :)

**Comment by EdmarPereira** [comment]
What version you are using? I have the same issue here in 3.0.3

**Comment by naser-baig-au4** [comment]
> 
> 
> What version you are using? I have the same issue here in 3.0.3 when I downgrade to 3.0.2 it works.

Hey @EdmarPereira, I am still on 2.1.5. I wonder why I wasn't updated to the latest version cause there's a ^ prefix in my package.json and it should automatically update the package to latest version I believe.

This should fix my issue I guess. I will test it and keep you guys posted.

**Comment by naser-baig-au4** [comment]
@EdmarPereira, yep that was the issue. I updated to 3.0.3 and it works just fine for me. I didn't even have to downgrade it to 3.0.2. I'll close this issue if you don't have anything to add.

**Comment by EdmarPereira** [comment]
You are welcome !!!
