### ISSUE TITLE
As new version of v3, is there any react way to clear input, unlike #12.

### ISSUE THREAD

**Issue by leopku** [Wolox/react-chat-widget#202]
Thanks for this awesome project.
It's so elegant, beautiful and easy to use.

I have confused after I trying this awesome component and reading readme.

Is there call backs for clearing input after user inputting message?
Or how to get the component of input, so I can clear it manually?

I had searched all issues. Only #12 is talking about input component.
But the answer is using css to clear input.
Is there any react way to do some thing?

**Comment by mcallegari10** [comment]
Hi @leopku ! Thank you for your kind words. As of v3.0.4 that should be fixed. There was an issue on the previous version with the message not being sent but #201 fixed it. Or you need something else I'm missing? 😄

**Comment by leopku** [comment]
Thanks for reply, @mcallegari10 .
I had test `3.0.4`, but it seems not work. Text user inputted still there after user click send button.

My testing code:
```js
  const handleSubmit = (evt) => {
    console.log(evt.target)
    console.dir(evt)
    console.log(`input message are: ${evt}`);
    addUserMessage(evt);
    addResponseMessage(evt);
    addLinkSnippet({
      title: 'himysql',
      link: 'https://l.himysql.com',
      target: '_blank',
    });
    setQuickButtons([{
      label: 'yes',
      value: 'yes',
    }, {
      label: 'no',
      value: 'no',
    }]);
  }
```

BTW: 
1. Is there necessary for add a callback for clearing text even if there are no bugs?
2. The param of `handleSubmit` is just a string, is there necessary for change it to event, so developers can get `event.target` to do more things?

Thanks again.

**Comment by naser-baig-au4** [comment]
Same issue for me as well. I upgraded from 2.1.5 to 3.0.4 and it doesn't work for me either.

**Comment by meksikann** [comment]
I've just updated to v.3.0.5 and it works perfect @naser-baig-au4

**Comment by leopku** [comment]
v3.0.5 had fixed.
I'll close this issue.

Thanks @meksikann .

**Comment by Bonfims** [comment]
handleSubmit is not given a event but a message
