### ISSUE TITLE
Make message sender box textarea instead of input

### ISSUE THREAD

**Issue by cmonteiro128** [Wolox/react-chat-widget#216]
I would like to add multi-line text input for the chat widget's sender box. Is there any easy way to do this? If not it seems like a pretty straight forward feature to add (add a multiLine prop that controls whether the underlying HTML element is a textarea or an input).

**Comment by mromauricio** [comment]
Hi Cris!  I hope you are all right. Did you find the solution for this issue or some other way? Thanks.

**Comment by cmonteiro128** [comment]
Hi @mromauricio 

I did not. I actually ended up just pulling the html and css out of this package and writing my own logic, the built in options were way to restrictive. Also, the way to add text messages made no sense, React is declarative and this sorta goes against that paradigm by using the addMessage methods or whatever they were called.

**Comment by mromauricio** [comment]
Thank you very much for the quick reply.
