### ISSUE TITLE
Navbar button not working well with widget

### ISSUE THREAD

**Issue by Paolo5150** [Wolox/react-chat-widget#234]
Hi guys, love the widget, I came across a small issue; I'm using react and the responsive Navbar. I noticed that when I reduce the screen size, and the navbar shrinks, the navbar button is just not clickable when the Widget is active.

Any way around this?

thanks

**Comment by CrisVega08** [comment]
Hi @Paolo5150, thanks for reporting this issue, we are going to close it because it is similar [# 211] (https://github.com/Wolox/react-chat-widget/issues/211), in the next version is solved
