### ISSUE TITLE
Close button doesn't trigger handleToggle when you have a custom launcher

### ISSUE THREAD

**Issue by dmsolutionz** [Wolox/react-chat-widget#236]
Hi there 👋 

When trying to implement this widget, I came across major flaws:

* The mobile implementation causes an overlay that stops people from being able to interact with the page, I implemented the vh fix as shown by other people. However this meant that on mobile, because there is a autofocus it causes the keyboard on devices to block out the close button, making it impossible to close the chat window.
* Because of the above I had to identify the widget container to set a height of 100% when you're on mobile & this window is active.
* I'm using a react hook to identify when a user clicks "open chat", to change the text to "close chat":
<img width="403" alt="Screen Shot 2020-11-30 at 5 02 46 pm" src="https://user-images.githubusercontent.com/12456115/100640086-e85ebd80-332d-11eb-8b1a-d914bc1b852b.png">
* However on mobile, when someone closes the chat in full screen mode it doesn't trigger the handleToggle function, therefore the component cannot identify that its been closed, ending up in a broken state when this happens.

Question:
Is there a way to trigger handleToggle() so custom launchers can be updated or is my implementation wrong, heres a snippet:

```
    const getCustomLauncher = handleToggle => {
      const [open, setOpen] = useState(false);

      // I dislike this but its a shame we cant control this any other way
      // Basically we need to append a new class to them to control how
      // mobile works, else it breaks, to test the old functionality
      // remove the custom launcher :)
      if (typeof document !== 'undefined') { // Nextjs can throw its undefined
        if (open) {
          const widget = document.getElementsByClassName('rcw-widget-container')[0];
          if (widget) widget.classList.add('cuckoo-chat-window-active');
        } else {
          const widget = document.getElementsByClassName('rcw-widget-container')[0];
          if (widget) widget.classList.remove('cuckoo-chat-window-active');
        }
      }

      return (
        <Fab
          onClick={() => {
            setOpen(!open);
            return handleToggle();
          }}
          variant="extended"
          size="medium"
          color="primary"
          aria-label="add"
        >
          {open ? (
            <>
              <CloseIcon /> Close chat
            </>
          ) : (
            <>
              <ChatIcon /> Chat with us
            </>
          )}
        </Fab>
      );
    };
```

**Comment by jotahws** [comment]
Did you manage any workaround for this issue?

**Comment by dmsolutionz** [comment]
@jotahws we killed our chatbot, I guess thats a workaround. This implementation just didn't work for us as it was too janky.
