### ISSUE TITLE
Restore timestamps from older chats.

### ISSUE THREAD

**Issue by jkoornneef** [Wolox/react-chat-widget#285]
Can addResponseMessage and addUserMessage be extended to pass in an optional timestamp Date.
I would like to continue a previous chat.  I can load the history from the database and use those two methods, but all messages will have the current time stamp due to:
`    timestamp: new Date(),`

**Comment by bnjr** [comment]
There is a PR for this https://github.com/Wolox/react-chat-widget/pull/275
@mcallegari10 request you to merge as it is a requirement from lot of us

**Comment by jkoornneef** [comment]
@bnjr  Thanks, I missed that branch.  I agree, a merge would be helpful for many.
