### ISSUE TITLE
design issue how can solve.

### ISSUE THREAD

**Issue by kaialsh705** [Wolox/react-chat-widget#288]
![Uploading Screenshot 2021-12-02 at 1.06.02 PM.png…]()

**Comment by kaialsh705** [comment]
![Screenshot 2021-12-02 at 1 06 02 PM](https://user-images.githubusercontent.com/59761075/144378828-2f8584e6-0512-486b-a67f-9666f7a3c58a.png)

**Comment by manthanbaranwal** [comment]
@kaialsh705 You probably have missed to import CSS. Try adding below line in your code.

`import 'react-chat-widget/lib/styles.css';`
