### ISSUE TITLE
Unable to create multiple instances, I imported widget in 2 different files, but they refer to same widget instance. How will I implement multi-user chat in this case?

### ISSUE THREAD

**Issue by gunjan4455** [Wolox/react-chat-widget#30]

**Comment by gunjan4455** [comment]
I imported widget in 2 different files, but they refer to same widget instance. How will I implement multi-user chat in this case?

**Comment by gunjan4455** [comment]
I imported widget in 2 different files, but they refer to same widget instance. How will I implement multi-user chat in this case?

**Comment by mcallegari10** [comment]
Hello! I'm sorry but multi chat is not yet supported. The way you are using it for that purpose won't work, what you are importing is 1 instance of the component and the store it provides.

**Comment by kimgysen** [comment]
Isn't this an enhancement request rather than a question? Nobody chats with 1 co-user, and it doesn't make sense to render private chat of all users in a single chatbox. Despite looking like a GREAT library, it renders it useless for my own use case from usability pov. Just IMO.

**Comment by fukemy** [comment]
does it support now?
 @kimgysen  do you found any lib better?

**Comment by kimgysen** [comment]
@fukemy I created my own widget with React back then. But I only used it for demo purpose, so I didn't publish it into a production widget sorry.

**Comment by fukemy** [comment]
> @fukemy I created my own widget with React back then. But I only used it for demo purpose, so I didn't publish it into a production widget sorry.

thanks you, can u give me some advices? I want to make multi chat widget like facebook did
