### ISSUE TITLE
Redux is using the wrong webpack NODE_ENV

### ISSUE THREAD

**Issue by udi-d** [Wolox/react-chat-widget#35]
after building and deploying the production bundle, I get this error:

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

anyone else encountered it?

**Comment by facundobringas** [comment]
facing same problem. Please help!

**Comment by Thomas-Negrault** [comment]
I have the same problem when building on production, I'm not a pro on Webpack config but the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) seems to be the solution: 
[SO: Passing environment-dependent variables in webpack
](https://stackoverflow.com/questions/30030031/passing-environment-dependent-variables-in-webpack)

If anyone could look into it and help us on this issue it would be great

**Comment by udi-d** [comment]
Define plugin wont help, because the process.env.NODE_ENV is correct.
It seems that Redux version which is bundled inside the project doesn't recognize it.

**Comment by mcallegari10** [comment]
Closing due to merged solution. If the problem persists, please feel free to reopen this issue. Thanks! :smile:

**Comment by udi-d** [comment]
Thank you!
