### ISSUE TITLE
Issue with custom styling. 

### ISSUE THREAD

**Issue by timtutt** [Wolox/react-chat-widget#42]
Having a some trouble modifying the styles. I've created a css file with the exact styles as listed below, and I import that after importing the widget, but unfortunately the widget base styles override them every time... Is there something I'm missing?

> To change the styles you need the widget to have, simply override the CSS classes wrapping them within the containers and add your own style to them! For expample:
> 
> ```
> .conversation-container > .header {
>   background-color: red;
> }
> 
> .message > .response {
>   background-color: black;
>   color: white;
> }
> ```

**Comment by lukejpreston** [comment]
I found you need to add `!important` to everything
