### ISSUE TITLE
Unable do override CSS

### ISSUE THREAD

**Issue by NewtonJoaquim** [Wolox/react-chat-widget#48]
Still about #21 .
Im trying the workaround solution by overriding the CSS, but been unable to successfully override it.
Could you be more clear about the overriding process, maybe by showing a step-by-step?

**Comment by mcallegari10** [comment]
Hi @NewtonJoaquim! It's already fixed with the PR #31 It's still yet to be uploaded to NPM. I'll try to bump the version tomorrow :smile: Sorry for the inconvenience!
