### ISSUE TITLE
White spaces only is not handled on handleNewUserMessage

### ISSUE THREAD

**Issue by nerdsquirrel** [Wolox/react-chat-widget#52]
Hi,
Thanks for the nice widget. The issue I am facing is, when user type only white spaces it also add on the chat window. I think it's shouldn't be the expected behavior.  From the source code I found:

```javascript
handleMessageSubmit = (event) => {
    event.preventDefault();
    const userInput = event.target.message.value;
    if (userInput) {
      this.props.dispatch(addUserMessage(userInput));
      this.props.handleNewUserMessage(userInput);
    }
    event.target.message.value = '';
}
```

I see it's only check the empty string not the only white spaces.  A possible fix might be:
```javascript
handleMessageSubmit = (event) => {
    event.preventDefault();
    const userInput = event.target.message.value;
    if (userInput.trim()) {
      this.props.dispatch(addUserMessage(userInput));
      this.props.handleNewUserMessage(userInput);
    }
    event.target.message.value = '';
}
```

**Comment by mcallegari10** [comment]
Oh, that's great, I didn't noticed that! Thanks for the heads up :smile:

**Comment by Dorian30** [comment]
Hi ! I'm going to close this. This issue has already been solved. 

https://github.com/Wolox/react-chat-widget/pull/103#issue-248985162
