### ISSUE TITLE
Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by denis0826** [Wolox/react-chat-widget#72]
If I add this `profileAvatar = {logo}` on the Widget Component, this will trigger an error.

Full code on App.js

```import React, { Component } from 'react';
import { Widget, addResponseMessage } from 'react-chat-widget';

import 'react-chat-widget/lib/styles.css';
import logo from './logo-small.png';

class App extends Component {
  componentDidMount() {
    addResponseMessage("Welcome to this awesome chat!");
  }
  handleNewUserMessage = (newMessage) => {
    console.log(`New message incomig! ${newMessage}`);
    // Now send the message throught the backend API
    // addResponseMessage(newMessage);
  }

  render() {
    return (
      <div className="App">
        <Widget
          handleNewUserMessage={this.handleNewUserMessage}
          profileAvatar = {logo}
          title="Test Title"
          subtitle="Test Sub"
        />
      </div>
    );
  }
}

export default App;
```

![err](https://user-images.githubusercontent.com/6411033/43386084-2455e33c-9415-11e8-9830-86db76ea1b66.PNG)

**Comment by mcallegari10** [comment]
Hi @denis0826 thank you very much for the heads up! That was my bad, merging something I shouldn't have, sorry 😅. Should be fix with version `2.1.4-1` already published.

**Comment by jiaqihuangrerere** [comment]
I think the problem is still there, can you double check it , thank you.

**Comment by mcallegari10** [comment]
This is from the dev environment of the version `2.1.4-1`. 

<img width="401" alt="screen shot 2018-07-30 at 18 53 02" src="https://user-images.githubusercontent.com/24418636/43425713-d46145c8-9429-11e8-94f5-bb19ba975fd2.png">

And I created a dummy project and tested the published version as well:

<img width="397" alt="screen shot 2018-07-30 at 18 59 19" src="https://user-images.githubusercontent.com/24418636/43426021-c581b334-942a-11e8-843f-4bdc0848c0b3.png">

@jiaqihuangrerere please check the version you are using or see if you can show a stack trace of the error

**Comment by jiaqihuangrerere** [comment]
2.1.4-1, this is my current version. Check you double check to see if there are any mistake, I still get the same error as mention in the post

**Comment by jiaqihuangrerere** [comment]
Also, in the web, it shows build is failed, please double check

https://www.npmjs.com/package/react-chat-widget
