### ISSUE TITLE
Can I use customLauncher via node_modules 'react-chat-widget' ?

### ISSUE THREAD

**Issue by Mouche3113** [Wolox/react-chat-widget#78]
Hello,

i dowloaded 'react-chat-widget' via npm ( npm i react-chat-widget ). After I import it in my file.

I want to have a custom launcher. 

Can I use customLauncher method or I need to git clone this project ?

Thank you.

**Comment by adantoscano** [comment]
Don't need to clone, just import your custom component and pass it through widget props

```javascript
import CustomComponent from 'urCustomComponent'

render() {
    return (
      <div className="App">
        <Widget
          handleNewUserMessage={this.handleNewUserMessage}
          customLauncher={CustomComponent}
        />
      </div>
    );
  }
```

**Comment by adantoscano** [comment]
@Mouche3113 the path of the component you want to use in your launcher

**Comment by Mouche3113** [comment]
No I misspoke ^^. I explain.

I called my folder (my component) 'CustomComponent', there is one index.tsx file in.

In my index.tsx file, what I should write to get my customLauncher working ?



In my App.tsx file,
I    `'import CustomComponent from 'urCustomComponent'`  ,

and in my render I have :
```
<Widget 
             handleNewUserMessage={this.handleNewUserMessage}
             title={strings.ChatTitle}
             customLauncher={CustomLauncher}
/>
```

Thank you.

**Comment by pabloferro** [comment]
Hey!

Your `CustomLauncher` we'll need a way of toggling the widget, I'll asume it accepts a prop named `onToggle` for the example. Also the custom launcher prop is named **launcher**.

The correct use of the **launcher** prop would be:

```jsx
<Widget 
  handleNewUserMessage={this.handleNewUserMessage}
  title={strings.ChatTitle}
  customLauncher={handleToggle => <CustomLauncher onToggle={handleToggle} />}
/>
```
