### ISSUE TITLE
How to add typing simulation.... 

### ISSUE THREAD

**Issue by kkhangv** [Wolox/react-chat-widget#99]
Hi guys - I am trying to add a little typing icon between responses. I wonder if there is a way we can put that into the CSS or jS?

**Comment by Ryuurock** [comment]
you can use "renderCustomComponent"

**Comment by thedrew12** [comment]
How would that work? I'm having trouble looking at the docs how/when to use `renderCustomComponent`.

**Comment by FaiqAriffin** [comment]
> How would that work? I'm having trouble looking at the docs and how/when to use `renderCustomComponent`.

Import the component class you want to use.
In this case there's a react loading library you can use here:
https://github.com/fakiolinho/react-loading

e.g import the react-loading as LOAD
renderCustomComponent(LOAD) ;

you can use the render method inside any functions within the class.

**Comment by thedrew12** [comment]
How would go about removing the custom component when you are done with it? Add a `ref` and then remove it from the DOM that way?

**Comment by thedrew12** [comment]
Here is how I did it to get a loading indictor:
```
  handleUserMessage = async (question: string) => {
    renderCustomComponent(this.Loader, { id: "chat-loader" }, true);
    const answer = await asyncCall(question);
    this.chatLoading.remove();
    addResponseMessage(answer);
  };
  Loader = (props: Object) => {
    return (
      <TypingWrapper
        {...props}
        ref={(el: HTMLDivElement) => (this.chatLoading = el)}
      >
        <TypingLoader />
      </TypingWrapper>
    );
  };
```
Another issue though, if I close the Widget and reopen, the messages are still there including my custom loader component. My guess is its still active in redux. So is there a way to remove the customComponent from redux state?

**Comment by Dorian30** [comment]
Hi guys! This have already been addressed in this issue: 

https://github.com/Wolox/react-chat-widget/issues/87

**Comment by dennyjohnk** [comment]
> How would go about removing the custom component when you are done with it? Add a `ref` and then remove it from the DOM that way?

How did you remove this custom component ?
